data:
    dataset: "NightRaindrop"
    image_size: 64 # Raindrop_DiT, RDiffusion, onego
    # image_size: 256 # ICRA, Uformer,atgan
    # image_size: 128 # IDT, restormer
    channels: 3
    num_workers: 8
    data_dir: "/home1/yeying/release/NightRainDrop/"
    conditional: True

model:
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    #-----------Raindrop_DiT, RDiffusion, onego, ICRA--------------
    patch_n: 4
    batch_size: 16
    # #---------IDT Uformer restormer--------------
    # patch_n: 1
    # batch_size: 4
    #-----------atgan--------------
    # patch_n: 1
    # batch_size: 32
    #-----------Raindrop_DiT, RDiffusion--------------
    n_epochs: 37042
    #n_epochs: 401
    n_iters: 20000000
    #snapshot_freq: 50
    snapshot_freq: 10000
    validation_freq: 10000

sampling:
    batch_size: 4
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    amsgrad: False
    eps: 0.00000001
